- name: windows playbook
  hosts: all
  vars: 
    local_admin_user: test-user
    local_admin_password: vault_local_admin_password
  vars_files:
  - vault.yml

  tasks:
  - name: ensure local admin account exists
    win_user:
      name: '{{ local_admin_username }}'
      password: '{{ local_admin_password }}'
      groups: Administrators
