- name: windows playbook
  hosts: all

  tasks:
  - name: ensure local admin account exists
    win_user:
      name: '{{ local_admin_username }}'
      password: '{{ local_admin_password }}'
      groups: Administrators
