- name: windows playbook
  hosts: all
  vars: 
    local_admin_user: test-user
    local_admin_password: vault_local_admin_password
  vars_files:
  - vault.yml

  tasks:
  - name: ensure local admin account exists
    win_user:
      name: '{{ local_admin_username }}'
      password: '{{ local_admin_password }}'
      groups: Administrators
    register: user_created
    failed_when: false

  - name: Get the hostname of the failed run
    set_fact: 
      hostname: "{{ ansible_hostname }}"
    when: user_created | failed 

  - name: Export results
    set_stats:
      data: 
        user_path: "{{ user_created.path }}"
        hostname: "{{ hostname }}"
